import java.util.Map;

public class Volumen extends ConversionLogica implements Pantalla.Convertidor {
    private static final Map<String, Double> conversionFactors = Map.ofEntries(
        // Conversión de Mililitros
        Map.entry("Mililitros->Mililitros", 1.0),
        Map.entry("Mililitros->Litros", 0.001),
        Map.entry("Mililitros->Galones", 0.000264172),
        Map.entry("Mililitros->Galón estadounidense", 0.000264172),
        Map.entry("Mililitros->Cuarto estadounidense", 0.00211338),
        Map.entry("Mililitros->Pinta estadounidense", 0.00211338),
        Map.entry("Mililitros->Taza americana oficial", 0.00422675),
        Map.entry("Mililitros->Onza líquida estadounidense", 0.033814),
        Map.entry("Mililitros->Cucharada estadounidense", 0.067628),
        Map.entry("Mililitros->Cucharadita estadounidense", 0.202884),
        Map.entry("Mililitros->Metro cúbico", 0.000001),
        Map.entry("Mililitros->Galón imperial", 0.000219969),
        Map.entry("Mililitros->Cuarto imperial", 0.00175975),
        Map.entry("Mililitros->Pinta imperial", 0.00351951),
        Map.entry("Mililitros->Taza imperial", 0.00351951),
        Map.entry("Mililitros->Onza líquida imperial", 0.0351951),
        Map.entry("Mililitros->Cucharada imperial", 0.067628),
        Map.entry("Mililitros->Cucharadita imperial", 0.202884),
        Map.entry("Mililitros->Pie cúbico", 0.000035315),
        Map.entry("Mililitros->Pulgada cúbica", 0.0610237),

        // Conversión de Litros
        Map.entry("Litros->Mililitros", 1000.0),
        Map.entry("Litros->Litros", 1.0),
        Map.entry("Litros->Galones", 0.264172),
        Map.entry("Litros->Galón estadounidense", 0.264172),
        Map.entry("Litros->Cuarto estadounidense", 4.22675),
        Map.entry("Litros->Pinta estadounidense", 2.11338),
        Map.entry("Litros->Taza americana oficial", 4.22675),
        Map.entry("Litros->Onza líquida estadounidense", 33.814),
        Map.entry("Litros->Cucharada estadounidense", 67.628),
        Map.entry("Litros->Cucharadita estadounidense", 202.884),
        Map.entry("Litros->Metro cúbico", 0.001),
        Map.entry("Litros->Galón imperial", 0.219969),
        Map.entry("Litros->Cuarto imperial", 2.11338),
        Map.entry("Litros->Pinta imperial", 4.22675),
        Map.entry("Litros->Taza imperial", 4.22675),
        Map.entry("Litros->Onza líquida imperial", 35.1951),
        Map.entry("Litros->Cucharada imperial", 67.628),
        Map.entry("Litros->Cucharadita imperial", 202.884),
        Map.entry("Litros->Pie cúbico", 0.0353147),
        Map.entry("Litros->Pulgada cúbica", 61.0237),

        // Conversión de Galones
        Map.entry("Galones->Mililitros", 3785.41),
        Map.entry("Galones->Litros", 3.78541),
        Map.entry("Galones->Galones", 1.0),
        Map.entry("Galones->Galón estadounidense", 1.0),
        Map.entry("Galones->Cuarto estadounidense", 4.0),
        Map.entry("Galones->Pinta estadounidense", 8.0),
        Map.entry("Galones->Taza americana oficial", 15.772),
        Map.entry("Galones->Onza líquida estadounidense", 128.0),
        Map.entry("Galones->Cucharada estadounidense", 256.0),
        Map.entry("Galones->Cucharadita estadounidense", 768.0),
        Map.entry("Galones->Metro cúbico", 0.00378541),
        Map.entry("Galones->Galón imperial", 0.832674),
        Map.entry("Galones->Cuarto imperial", 3.32869),
        Map.entry("Galones->Pinta imperial", 6.61734),
        Map.entry("Galones->Taza imperial", 7.99363),
        Map.entry("Galones->Onza líquida imperial", 105.669),
        Map.entry("Galones->Cucharada imperial", 224.0),
        Map.entry("Galones->Cucharadita imperial", 672.0),
        Map.entry("Galones->Pie cúbico", 0.133681),
        Map.entry("Galones->Pulgada cúbica", 231.0),

        // Conversión de Galón estadounidense
        Map.entry("Galón estadounidense->Mililitros", 3785.41),
        Map.entry("Galón estadounidense->Litros", 3.78541),
        Map.entry("Galón estadounidense->Galones", 1.0),
        Map.entry("Galón estadounidense->Galón estadounidense", 1.0),
        Map.entry("Galón estadounidense->Cuarto estadounidense", 4.0),
        Map.entry("Galón estadounidense->Pinta estadounidense", 8.0),
        Map.entry("Galón estadounidense->Taza americana oficial", 15.772),
        Map.entry("Galón estadounidense->Onza líquida estadounidense", 128.0),
        Map.entry("Galón estadounidense->Cucharada estadounidense", 256.0),
        Map.entry("Galón estadounidense->Cucharadita estadounidense", 768.0),
        Map.entry("Galón estadounidense->Metro cúbico", 0.00378541),
        Map.entry("Galón estadounidense->Galón imperial", 0.832674),
        Map.entry("Galón estadounidense->Cuarto imperial", 3.32869),
        Map.entry("Galón estadounidense->Pinta imperial", 6.61734),
        Map.entry("Galón estadounidense->Taza imperial", 7.99363),
        Map.entry("Galón estadounidense->Onza líquida imperial", 105.669),
        Map.entry("Galón estadounidense->Cucharada imperial", 224.0),
        Map.entry("Galón estadounidense->Cucharadita imperial", 672.0),
        Map.entry("Galón estadounidense->Pie cúbico", 0.133681),
        Map.entry("Galón estadounidense->Pulgada cúbica", 231.0),

        // Conversión de Cuarto estadounidense
        Map.entry("Cuarto estadounidense->Mililitros", 946.353),
        Map.entry("Cuarto estadounidense->Litros", 0.946353),
        Map.entry("Cuarto estadounidense->Galones", 0.25),
        Map.entry("Cuarto estadounidense->Galón estadounidense", 0.25),
        Map.entry("Cuarto estadounidense->Cuarto estadounidense", 1.0),
        Map.entry("Cuarto estadounidense->Pinta estadounidense", 2.0),
        Map.entry("Cuarto estadounidense->Taza americana oficial", 4.0),
        Map.entry("Cuarto estadounidense->Onza líquida estadounidense", 32.0),
        Map.entry("Cuarto estadounidense->Cucharada estadounidense", 64.0),
        Map.entry("Cuarto estadounidense->Cucharadita estadounidense", 192.0),
        Map.entry("Cuarto estadounidense->Metro cúbico", 0.000946353),
        Map.entry("Cuarto estadounidense->Galón imperial", 0.219969),
        Map.entry("Cuarto estadounidense->Cuarto imperial", 1.0),
        Map.entry("Cuarto estadounidense->Pinta imperial", 2.0),
        Map.entry("Cuarto estadounidense->Taza imperial", 4.0),
        Map.entry("Cuarto estadounidense->Onza líquida imperial", 32.0),
        Map.entry("Cuarto estadounidense->Cucharada imperial", 64.0),
        Map.entry("Cuarto estadounidense->Cucharadita imperial", 192.0),
        Map.entry("Cuarto estadounidense->Pie cúbico", 0.0003285),
        Map.entry("Cuarto estadounidense->Pulgada cúbica", 57.75),

        // Conversión de Pinta estadounidense
        Map.entry("Pinta estadounidense->Mililitros", 473.176),
        Map.entry("Pinta estadounidense->Litros", 0.473176),
        Map.entry("Pinta estadounidense->Galones", 0.125),
        Map.entry("Pinta estadounidense->Galón estadounidense", 0.125),
        Map.entry("Pinta estadounidense->Cuarto estadounidense", 0.5),
        Map.entry("Pinta estadounidense->Pinta estadounidense", 1.0),
        Map.entry("Pinta estadounidense->Taza americana oficial", 2.0),
        Map.entry("Pinta estadounidense->Onza líquida estadounidense", 16.0),
        Map.entry("Pinta estadounidense->Cucharada estadounidense", 32.0),
        Map.entry("Pinta estadounidense->Cucharadita estadounidense", 96.0),
        Map.entry("Pinta estadounidense->Metro cúbico", 0.000473176),
        Map.entry("Pinta estadounidense->Galón imperial", 0.10984),
        Map.entry("Pinta estadounidense->Cuarto imperial", 0.5),
        Map.entry("Pinta estadounidense->Pinta imperial", 1.0),
        Map.entry("Pinta estadounidense->Taza imperial", 1.0),
        Map.entry("Pinta estadounidense->Onza líquida imperial", 16.0),
        Map.entry("Pinta estadounidense->Cucharada imperial", 32.0),
        Map.entry("Pinta estadounidense->Cucharadita imperial", 96.0),
        Map.entry("Pinta estadounidense->Pie cúbico", 0.0001654),
        Map.entry("Pinta estadounidense->Pulgada cúbica", 28.875),
 
        //Pinta imperial
        Map.entry("Pinta imperial->Mililitros", 568.261),
        Map.entry("Pinta imperial->Litros", 0.568261),
        Map.entry("Pinta imperial->Galones", 0.125),
        Map.entry("Pinta imperial->Galón estadounidense", 0.15012),
        Map.entry("Pinta imperial->Cuarto estadounidense", 0.600475),
        Map.entry("Pinta imperial->Pinta estadounidense", 1.20095),
        Map.entry("Pinta imperial->Taza americana oficial", 2.4019),
        Map.entry("Pinta imperial->Onza líquida estadounidense", 19.2152),
        Map.entry("Pinta imperial->Cucharada estadounidense", 38.4304),
        Map.entry("Pinta imperial->Cucharadita estadounidense", 115.291),
        Map.entry("Pinta imperial->Metro cúbico", 0.000568261),
        Map.entry("Pinta imperial->Galón imperial", 0.125),
        Map.entry("Pinta imperial->Cuarto imperial", 0.5),
        Map.entry("Pinta imperial->Pinta imperial", 1.0),
        Map.entry("Pinta imperial->Taza imperial", 2.0),
        Map.entry("Pinta imperial->Onza líquida imperial", 20.0),
        Map.entry("Pinta imperial->Cucharada imperial", 32.0),
        Map.entry("Pinta imperial->Cucharadita imperial", 96.0),
        Map.entry("Pinta imperial->Pie cúbico", 0.00002007),
        Map.entry("Pinta imperial->Pulgada cúbica", 34.6774),

        // Conversión de Taza americana oficial
        Map.entry("Taza americana oficial->Mililitros", 236.588),
        Map.entry("Taza americana oficial->Litros", 0.236588),
        Map.entry("Taza americana oficial->Galones", 0.0625),
        Map.entry("Taza americana oficial->Galón estadounidense", 0.0625),
        Map.entry("Taza americana oficial->Cuarto estadounidense", 0.25),
        Map.entry("Taza americana oficial->Pinta estadounidense", 0.5),
        Map.entry("Taza americana oficial->Taza americana oficial", 1.0),
        Map.entry("Taza americana oficial->Onza líquida estadounidense", 8.0),
        Map.entry("Taza americana oficial->Cucharada estadounidense", 16.0),
        Map.entry("Taza americana oficial->Cucharadita estadounidense", 48.0),
        Map.entry("Taza americana oficial->Metro cúbico", 0.000236588),
        Map.entry("Taza americana oficial->Galón imperial", 0.052042),
        Map.entry("Taza americana oficial->Cuarto imperial", 0.25),
        Map.entry("Taza americana oficial->Pinta imperial", 0.5),
        Map.entry("Taza americana oficial->Taza imperial", 0.5),
        Map.entry("Taza americana oficial->Onza líquida imperial", 8.0),
        Map.entry("Taza americana oficial->Cucharada imperial", 16.0),
        Map.entry("Taza americana oficial->Cucharadita imperial", 48.0),
        Map.entry("Taza americana oficial->Pie cúbico", 0.00008612),
        Map.entry("Taza americana oficial->Pulgada cúbica", 14.4375),
        
        //Taza imperial
        Map.entry("Taza imperial->Mililitros", 284.131),
        Map.entry("Taza imperial->Litros", 0.284131),
        Map.entry("Taza imperial->Galones", 0.0625),
        Map.entry("Taza imperial->Galón estadounidense", 0.07506),
        Map.entry("Taza imperial->Cuarto estadounidense", 0.300237),
        Map.entry("Taza imperial->Pinta estadounidense", 0.600475),
        Map.entry("Taza imperial->Taza americana oficial", 1.20095),
        Map.entry("Taza imperial->Onza líquida estadounidense", 9.6076),
        Map.entry("Taza imperial->Cucharada estadounidense", 19.2152),
        Map.entry("Taza imperial->Cucharadita estadounidense", 57.6457),
        Map.entry("Taza imperial->Metro cúbico", 0.000284131),
        Map.entry("Taza imperial->Galón imperial", 0.0625),
        Map.entry("Taza imperial->Cuarto imperial", 0.25),
        Map.entry("Taza imperial->Pinta imperial", 0.5),
        Map.entry("Taza imperial->Taza imperial", 1.0),
        Map.entry("Taza imperial->Onza líquida imperial", 10.0),
        Map.entry("Taza imperial->Cucharada imperial", 16.0),
        Map.entry("Taza imperial->Cucharadita imperial", 48.0),
        Map.entry("Taza imperial->Pie cúbico", 0.00001003),
        Map.entry("Taza imperial->Pulgada cúbica", 17.3387),

        // Conversión de Onza líquida estadounidense
        Map.entry("Onza líquida estadounidense->Mililitros", 29.5735),
        Map.entry("Onza líquida estadounidense->Litros", 0.0295735),
        Map.entry("Onza líquida estadounidense->Galones", 0.0078125),
        Map.entry("Onza líquida estadounidense->Galón estadounidense", 0.0078125),
        Map.entry("Onza líquida estadounidense->Cuarto estadounidense", 0.03125),
        Map.entry("Onza líquida estadounidense->Pinta estadounidense", 0.0625),
        Map.entry("Onza líquida estadounidense->Taza americana oficial", 0.125),
        Map.entry("Onza líquida estadounidense->Onza líquida estadounidense", 1.0),
        Map.entry("Onza líquida estadounidense->Cucharada estadounidense", 2.0),
        Map.entry("Onza líquida estadounidense->Cucharadita estadounidense", 6.0),
        Map.entry("Onza líquida estadounidense->Metro cúbico", 0.0000295735),
        Map.entry("Onza líquida estadounidense->Galón imperial", 0.006196),
        Map.entry("Onza líquida estadounidense->Cuarto imperial", 0.03125),
        Map.entry("Onza líquida estadounidense->Pinta imperial", 0.0625),
        Map.entry("Onza líquida estadounidense->Taza imperial", 0.125),
        Map.entry("Onza líquida estadounidense->Onza líquida imperial", 0.0351951),
        Map.entry("Onza líquida estadounidense->Cucharada imperial", 0.0625),
        Map.entry("Onza líquida estadounidense->Cucharadita imperial", 0.1875),
        Map.entry("Onza líquida estadounidense->Pie cúbico", 0.00001731),
        Map.entry("Onza líquida estadounidense->Pulgada cúbica", 1.80469),

        // Conversión de Cucharada estadounidense
        Map.entry("Cucharada estadounidense->Mililitros", 14.7868),
        Map.entry("Cucharada estadounidense->Litros", 0.0147868),
        Map.entry("Cucharada estadounidense->Galones", 0.00390625),
        Map.entry("Cucharada estadounidense->Galón estadounidense", 0.00390625),
        Map.entry("Cucharada estadounidense->Cuarto estadounidense", 0.015625),
        Map.entry("Cucharada estadounidense->Pinta estadounidense", 0.03125),
        Map.entry("Cucharada estadounidense->Taza americana oficial", 0.0625),
        Map.entry("Cucharada estadounidense->Onza líquida estadounidense", 0.676280),
        Map.entry("Cucharada estadounidense->Cucharada estadounidense", 1.0),
        Map.entry("Cucharada estadounidense->Cucharadita estadounidense", 3.0),
        Map.entry("Cucharada estadounidense->Metro cúbico", 0.0000147868),
        Map.entry("Cucharada estadounidense->Galón imperial", 0.00087648),
        Map.entry("Cucharada estadounidense->Cuarto imperial", 0.015625),
        Map.entry("Cucharada estadounidense->Pinta imperial", 0.03125),
        Map.entry("Cucharada estadounidense->Taza imperial", 0.0625),
        Map.entry("Cucharada estadounidense->Onza líquida imperial", 0.0208033),
        Map.entry("Cucharada estadounidense->Cucharada imperial", 0.0625),
        Map.entry("Cucharada estadounidense->Cucharadita imperial", 0.1875),
        Map.entry("Cucharada estadounidense->Pie cúbico", 0.00000855),
        Map.entry("Cucharada estadounidense->Pulgada cúbica", 0.87492),

        // Conversión de Cucharadita estadounidense
        Map.entry("Cucharadita estadounidense->Mililitros", 4.92892),
        Map.entry("Cucharadita estadounidense->Litros", 0.00492892),
        Map.entry("Cucharadita estadounidense->Galones", 0.00130208),
        Map.entry("Cucharadita estadounidense->Galón estadounidense", 0.00130208),
        Map.entry("Cucharadita estadounidense->Cuarto estadounidense", 0.00520833),
        Map.entry("Cucharadita estadounidense->Pinta estadounidense", 0.0104167),
        Map.entry("Cucharadita estadounidense->Taza americana oficial", 0.0208333),
        Map.entry("Cucharadita estadounidense->Onza líquida estadounidense", 0.202884),
        Map.entry("Cucharadita estadounidense->Cucharada estadounidense", 0.333333),
        Map.entry("Cucharadita estadounidense->Cucharadita estadounidense", 1.0),
        Map.entry("Cucharadita estadounidense->Metro cúbico", 0.00000492892),
        Map.entry("Cucharadita estadounidense->Galón imperial", 0.0002629),
        Map.entry("Cucharadita estadounidense->Cuarto imperial", 0.00520833),
        Map.entry("Cucharadita estadounidense->Pinta imperial", 0.0104167),
        Map.entry("Cucharadita estadounidense->Taza imperial", 0.0208333),
        Map.entry("Cucharadita estadounidense->Onza líquida imperial", 0.00681249),
        Map.entry("Cucharadita estadounidense->Cucharada imperial", 0.0208333),
        Map.entry("Cucharadita estadounidense->Cucharadita imperial", 0.0625),
        Map.entry("Cucharadita estadounidense->Pie cúbico", 0.00000283),
        Map.entry("Cucharadita estadounidense->Pulgada cúbica", 0.29363),

        // Conversión de Metro cúbico
        Map.entry("Metro cúbico->Mililitros", 1000000.0),
        Map.entry("Metro cúbico->Litros", 1000.0),
        Map.entry("Metro cúbico->Galones", 264.172),
        Map.entry("Metro cúbico->Galón estadounidense", 264.172),
        Map.entry("Metro cúbico->Cuarto estadounidense", 4226.75),
        Map.entry("Metro cúbico->Pinta estadounidense", 2113.38),
        Map.entry("Metro cúbico->Taza americana oficial", 422.675),
        Map.entry("Metro cúbico->Onza líquida estadounidense", 33814.0),
        Map.entry("Metro cúbico->Cucharada estadounidense", 67628.0),
        Map.entry("Metro cúbico->Cucharadita estadounidense", 202884.0),
        Map.entry("Metro cúbico->Metro cúbico", 1.0),
        Map.entry("Metro cúbico->Galón imperial", 219.969),
        Map.entry("Metro cúbico->Cuarto imperial", 422.675),
        Map.entry("Metro cúbico->Pinta imperial", 844.25),
        Map.entry("Metro cúbico->Taza imperial", 1000.0),
        Map.entry("Metro cúbico->Onza líquida imperial", 33814.0),
        Map.entry("Metro cúbico->Cucharada imperial", 67628.0),
        Map.entry("Metro cúbico->Cucharadita imperial", 202884.0),
        Map.entry("Metro cúbico->Pie cúbico", 35.3147),
        Map.entry("Metro cúbico->Pulgada cúbica", 61023.7),

        // Conversión de Galón imperial
        Map.entry("Galón imperial->Mililitros", 4546.09),
        Map.entry("Galón imperial->Litros", 4.54609),
        Map.entry("Galón imperial->Galones", 1.0),
        Map.entry("Galón imperial->Galón estadounidense", 1.20095),
        Map.entry("Galón imperial->Cuarto estadounidense", 4.0),
        Map.entry("Galón imperial->Pinta estadounidense", 8.0),
        Map.entry("Galón imperial->Taza americana oficial", 16.0),
        Map.entry("Galón imperial->Onza líquida estadounidense", 128.0),
        Map.entry("Galón imperial->Cucharada estadounidense", 256.0),
        Map.entry("Galón imperial->Cucharadita estadounidense", 768.0),
        Map.entry("Galón imperial->Metro cúbico", 0.000454609),
        Map.entry("Galón imperial->Galón imperial", 1.0),
        Map.entry("Galón imperial->Cuarto imperial", 4.0),
        Map.entry("Galón imperial->Pinta imperial", 8.0),
        Map.entry("Galón imperial->Taza imperial", 16.0),
        Map.entry("Galón imperial->Onza líquida imperial", 128.0),
        Map.entry("Galón imperial->Cucharada imperial", 256.0),
        Map.entry("Galón imperial->Cucharadita imperial", 768.0),
        Map.entry("Galón imperial->Pie cúbico", 0.00011983),
        Map.entry("Galón imperial->Pulgada cúbica", 277.419),

        // Conversión de Cuarto imperial
        Map.entry("Cuarto imperial->Mililitros", 1136.52),
        Map.entry("Cuarto imperial->Litros", 1.13652),
        Map.entry("Cuarto imperial->Galones", 0.25),
        Map.entry("Cuarto imperial->Galón estadounidense", 0.300781),
        Map.entry("Cuarto imperial->Cuarto estadounidense", 1.0),
        Map.entry("Cuarto imperial->Pinta estadounidense", 2.0),
        Map.entry("Cuarto imperial->Taza americana oficial", 4.0),
        Map.entry("Cuarto imperial->Onza líquida estadounidense", 32.0),
        Map.entry("Cuarto imperial->Cucharada estadounidense", 64.0),
        Map.entry("Cuarto imperial->Cucharadita estadounidense", 192.0),
        Map.entry("Cuarto imperial->Metro cúbico", 0.00113652),
        Map.entry("Cuarto imperial->Galón imperial", 0.25),
        Map.entry("Cuarto imperial->Cuarto imperial", 1.0),
        Map.entry("Cuarto imperial->Pinta imperial", 2.0),
        Map.entry("Cuarto imperial->Taza imperial", 4.0),
        Map.entry("Cuarto imperial->Onza líquida imperial", 32.0),
        Map.entry("Cuarto imperial->Cucharada imperial", 64.0),
        Map.entry("Cuarto imperial->Cucharadita imperial", 192.0),
        Map.entry("Cuarto imperial->Pie cúbico", 0.00005961),
        Map.entry("Cuarto imperial->Pulgada cúbica", 68.5793),
            
        Map.entry("Onza líquida imperial->Mililitros", 28.4131),
        Map.entry("Onza líquida imperial->Litros", 0.0284131),
        Map.entry("Onza líquida imperial->Galones", 0.00625),
        Map.entry("Onza líquida imperial->Galón estadounidense", 0.00750594),
        Map.entry("Onza líquida imperial->Cuarto estadounidense", 0.0300238),
        Map.entry("Onza líquida imperial->Pinta estadounidense", 0.0600475),
        Map.entry("Onza líquida imperial->Taza americana oficial", 0.120095),
        Map.entry("Onza líquida imperial->Onza líquida estadounidense", 0.96076),
        Map.entry("Onza líquida imperial->Cucharada estadounidense", 1.92152),
        Map.entry("Onza líquida imperial->Cucharadita estadounidense", 5.76457),
        Map.entry("Onza líquida imperial->Metro cúbico", 0.0000284131),
        Map.entry("Onza líquida imperial->Galón imperial", 0.00625),
        Map.entry("Onza líquida imperial->Cuarto imperial", 0.025),
        Map.entry("Onza líquida imperial->Pinta imperial", 0.05),
        Map.entry("Onza líquida imperial->Taza imperial", 0.1),
        Map.entry("Onza líquida imperial->Onza líquida imperial", 1.0),
        Map.entry("Onza líquida imperial->Cucharada imperial", 1.6),
        Map.entry("Onza líquida imperial->Cucharadita imperial", 4.8),
        Map.entry("Onza líquida imperial->Pie cúbico", 0.000001003),
        Map.entry("Onza líquida imperial->Pulgada cúbica", 1.73387),
                
        Map.entry("Cucharada imperial->Mililitros", 17.7582),
        Map.entry("Cucharada imperial->Litros", 0.0177582),
        Map.entry("Cucharada imperial->Galones", 0.00390625),
        Map.entry("Cucharada imperial->Galón estadounidense", 0.00469121),
        Map.entry("Cucharada imperial->Cuarto estadounidense", 0.0187648),
        Map.entry("Cucharada imperial->Pinta estadounidense", 0.0375296),
        Map.entry("Cucharada imperial->Taza americana oficial", 0.0750593),
        Map.entry("Cucharada imperial->Onza líquida estadounidense", 0.600475),
        Map.entry("Cucharada imperial->Cucharada estadounidense", 1.20095),
        Map.entry("Cucharada imperial->Cucharadita estadounidense", 3.60285),
        Map.entry("Cucharada imperial->Metro cúbico", 0.0000177582),
        Map.entry("Cucharada imperial->Galón imperial", 0.00390625),
        Map.entry("Cucharada imperial->Cuarto imperial", 0.015625),
        Map.entry("Cucharada imperial->Pinta imperial", 0.03125),
        Map.entry("Cucharada imperial->Taza imperial", 0.0625),
        Map.entry("Cucharada imperial->Onza líquida imperial", 0.625),
        Map.entry("Cucharada imperial->Cucharada imperial", 1.0),
        Map.entry("Cucharada imperial->Cucharadita imperial", 3.0),
        Map.entry("Cucharada imperial->Pie cúbico", 0.000000627),
        Map.entry("Cucharada imperial->Pulgada cúbica", 1.08367),
                
        Map.entry("Cucharadita imperial->Mililitros", 5.91939),
        Map.entry("Cucharadita imperial->Litros", 0.00591939),
        Map.entry("Cucharadita imperial->Galones", 0.00130208),
        Map.entry("Cucharadita imperial->Galón estadounidense", 0.00156374),
        Map.entry("Cucharadita imperial->Cuarto estadounidense", 0.00625498),
        Map.entry("Cucharadita imperial->Pinta estadounidense", 0.0125099),
        Map.entry("Cucharadita imperial->Taza americana oficial", 0.0250198),
        Map.entry("Cucharadita imperial->Onza líquida estadounidense", 0.200158),
        Map.entry("Cucharadita imperial->Cucharada estadounidense", 0.400317),
        Map.entry("Cucharadita imperial->Cucharadita estadounidense", 1.20095),
        Map.entry("Cucharadita imperial->Metro cúbico", 0.00000591939),
        Map.entry("Cucharadita imperial->Galón imperial", 0.00130208),
        Map.entry("Cucharadita imperial->Cuarto imperial", 0.00520833),
        Map.entry("Cucharadita imperial->Pinta imperial", 0.0104167),
        Map.entry("Cucharadita imperial->Taza imperial", 0.0208333),
        Map.entry("Cucharadita imperial->Onza líquida imperial", 0.208333),
        Map.entry("Cucharadita imperial->Cucharada imperial", 0.333333),
        Map.entry("Cucharadita imperial->Cucharadita imperial", 1.0),
        Map.entry("Cucharadita imperial->Pie cúbico", 0.000000209),
        Map.entry("Cucharadita imperial->Pulgada cúbica", 0.361224),
                
        Map.entry("Pie cúbico->Mililitros", 28316.8),
        Map.entry("Pie cúbico->Litros", 28.3168),
        Map.entry("Pie cúbico->Galones", 7.48052),
        Map.entry("Pie cúbico->Galón estadounidense", 7.48052),
        Map.entry("Pie cúbico->Cuarto estadounidense", 29.9221),
        Map.entry("Pie cúbico->Pinta estadounidense", 59.8442),
        Map.entry("Pie cúbico->Taza americana oficial", 119.688),
        Map.entry("Pie cúbico->Onza líquida estadounidense", 957.506),
        Map.entry("Pie cúbico->Cucharada estadounidense", 1915.01),
        Map.entry("Pie cúbico->Cucharadita estadounidense", 5745.04),
        Map.entry("Pie cúbico->Metro cúbico", 0.0283168),
        Map.entry("Pie cúbico->Galón imperial", 6.22884),
        Map.entry("Pie cúbico->Cuarto imperial", 24.9153),
        Map.entry("Pie cúbico->Pinta imperial", 49.8307),
        Map.entry("Pie cúbico->Taza imperial", 99.6614),
        Map.entry("Pie cúbico->Onza líquida imperial", 996.614),
        Map.entry("Pie cúbico->Cucharada imperial", 1594.58),
        Map.entry("Pie cúbico->Cucharadita imperial", 4783.75),
        Map.entry("Pie cúbico->Pie cúbico", 1.0),
        Map.entry("Pie cúbico->Pulgada cúbica", 1728.0),
                
        Map.entry("Pulgada cúbica->Mililitros", 16.3871),
        Map.entry("Pulgada cúbica->Litros", 0.0163871),
        Map.entry("Pulgada cúbica->Galones", 0.004329),
        Map.entry("Pulgada cúbica->Galón estadounidense", 0.004329),
        Map.entry("Pulgada cúbica->Cuarto estadounidense", 0.017316),
        Map.entry("Pulgada cúbica->Pinta estadounidense", 0.034632),
        Map.entry("Pulgada cúbica->Taza americana oficial", 0.069264),
        Map.entry("Pulgada cúbica->Onza líquida estadounidense", 0.554113),
        Map.entry("Pulgada cúbica->Cucharada estadounidense", 1.10823),
        Map.entry("Pulgada cúbica->Cucharadita estadounidense", 3.3247),
        Map.entry("Pulgada cúbica->Metro cúbico", 0.0000163871),
        Map.entry("Pulgada cúbica->Galón imperial", 0.00360465),
        Map.entry("Pulgada cúbica->Cuarto imperial", 0.0144186),
        Map.entry("Pulgada cúbica->Pinta imperial", 0.0288372),
        Map.entry("Pulgada cúbica->Taza imperial", 0.0576744),
        Map.entry("Pulgada cúbica->Onza líquida imperial", 0.576744),
        Map.entry("Pulgada cúbica->Cucharada imperial", 0.92279),
        Map.entry("Pulgada cúbica->Cucharadita imperial", 2.76837),
        Map.entry("Pulgada cúbica->Pie cúbico", 0.000578704),
        Map.entry("Pulgada cúbica->Pulgada cúbica", 1.0)
                
        );
    @Override
    public String convertir(double valor, String unidadEntrada, String unidadSalida) {
        String conversionKey = unidadEntrada + "->" + unidadSalida;
        double factor = conversionFactors.getOrDefault(conversionKey, 1.0);
        return convertirUnidades(valor, factor);  // Usa el método de ConversionLogica
    }
}